version: "1.0"
stages:
  - "clone"
  - "testimage"
  - "test"
  - "build"
  - "integration"
  - "push"
  - "deploy"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "Sri-R/cf-python-1"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  UnitTestDockerImage:
    title: Building Test image
    type: build
    stage: 'testimage'
    image_name: test-image
    tag: 'master'
    dockerfile: Dockerfile.test
  UnitTests:
    title: Running Unit tests
    stage: test
    image: '${{UnitTestDockerImage}}'
    commands:
      - python test_basic.py
  build:
    title: "Building Docker Image"
    type: "build"
    image_name: "Sri/cf-python"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
  push:
    title: "Pushing image to cfcr"
    type: "push"
    image_name: "Sri/cf-python"
    registry: "cfcr"
    candidate: "${{build}}"
    tag: "latest"
    stage: "push"

  deploy_ecs:
    image: codefresh/cf-deploy-ecs
    commands:
      - cfecs-update --image-name Sri/cf-python --image-tag 'latest' us-east-1 test python
    environment:
      - AWS_ACCESS_KEY_ID=${{AWS_ACCESS_KEY_ID}}
      - AWS_SECRET_ACCESS_KEY=${{AWS_SECRET_ACCESS_KEY}}
    when:
      branch:
        only:
          - master
    stage: "deploy"
